services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8081:80"
    links:
      - php
    restart: always
    labels:
      - traefik.enable=true
      - "traefik.http.middlewares.vcrypto-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.vcrypto-redirect.redirectscheme.permanent=true"
      # HTTP
      - "traefik.http.routers.vcrypto-nginx.rule=Host(`vcrypto.tonyo.info`)"
      - "traefik.http.routers.vcrypto-nginx.entrypoints=http"
      - "traefik.http.routers.vcrypto-nginx.middlewares=vcrypto-redirect"
      # HTTPS
      - "traefik.http.routers.vcrypto-nginx-secure.rule=Host(`vcrypto.tonyo.info`)"
      - "traefik.http.routers.vcrypto-nginx-secure.entryPoints=https"
      - "traefik.http.routers.vcrypto-nginx-secure.tls=true"
      - "traefik.http.routers.vcrypto-nginx-secure.tls.certresolver=letsencrypt"
  php:
    build:
      context: .
      dockerfile: website/Dockerfile
    ports:
      - "9000:9000"
    restart: always
