services:
  nginx:
    #  build: ./nginx/
    image: nginx:1.20
    ports:
      - "80:80"
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./website:/var/www/html
    links:
      - php

  php:
    build: ./website/
    expose:
      - "9000:9000"
    volumes:
      - ./website:/var/www/html
