services:
  nginx:
    image: tonyo/vcrypto-nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    x-ports:
      - vcrypto.tonyo.info:80/https
    restart: always
  php:
    image: tonyo/vcrypto-app
    build:
      context: .
      dockerfile: website/Dockerfile
    restart: always
