services:
  nginx:
    image: nginx:1.20
    ports:
      - "80:80"
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./website:/var/www/html:ro
    links:
      - php

  php:
    image: php:5.5-fpm
    expose:
      - "9000:9000"
    volumes:
      - ./website:/var/www/html:ro
